name: Push to ECR

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: |
            keboola/kds-team.processor-json2csv:${{ github.ref_name }}
            keboola/kds-team.processor-json2csv:latest

      - name: Push to ECR
        uses: keboola/action-push-to-ecr@master
        with:
          vendor: kds-team
          app_id: kds-team.processor-json2csv
          username: kds-team+processor_json2csv_github_actions
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ github.ref_name }}
          push_latest: true
          source_image: keboola/kds-team.processor-json2csv
        env:
          KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
